### ISSUE TITLE
Could rumble pak support exist?

### ISSUE THREAD

**Issue by remy** [spiritualized1997/openFPGA-GB-GBC#14]
I've got an EZ Flash DE which supports switching itself into a rumble pak. But using this as an external rumble pak on GB(C) games does nothing.

I wondered if the core could be modified to look for the rumble pak and redirect the signal that? I've really no idea how this would work internally (I've got some understanding of how FPGA chips work and their programming, but not sure where this kind of thing would live…maybe it actually requires a patch to the game being used…).

Any thoughts on this even being possible?

**Comment by KeenIIDX** [comment]
The core does that, and works with the official DS Rumble Pak. There’s an issue with the EZ Flash ODE. I filed this over on the GBA core, I should have thought to file it here as well. https://github.com/spiritualized1997/openFPGA-GBA/issues/6

**Comment by remy** [comment]
Oh cool. Okay, I'd consider this issue a dupe of #6 so I'll close it - thanks for the follow up 👍
