### ISSUE TITLE
Sorting ROMs into Subfolders

### ISSUE THREAD

**Issue by SonOfKorriban** [spiritualized1997/openFPGA-GB-GBC#30]
Servus
i really, really want to sort my ROM Set into Subfolders named like this: "A", "B", "C".... you know what comes next? Right. "F"....

Okay. so i decided to put all my ROMs inside the Path Assets\gb\common into these Folders. Unfortunately, it doesn't work. 
If i choose a ROM inside one of those Folders, it jumps back and the analogue shows only empty Folders. 
I am not able to start any ROM there. 

Is there any Possibility to sort my ROMs? Can this one added as a feature in the future? Thanks! :)

![image](https://user-images.githubusercontent.com/39160000/209861799-32cb713c-3799-485f-8375-82129d4c8393.png)

**Comment by MaciekBaron** [comment]
This should work, you must have done something wrong (I do exactly that).
Also, this is not core specific.

**Comment by SonOfKorriban** [comment]
Any Idea, what could go wrong here? I am absoluteley clueless.
Before adding these Folders all just worked fine

**Comment by MaciekBaron** [comment]
Can't tell without more details. The only difference I can see is that I
don't use # as one of the folder names.

**Comment by SonOfKorriban** [comment]
Closed. It was my own fault since there was missing an important BIOS file
