### ISSUE TITLE
GB compatible GBC games do not show up under Gameboy core

### ISSUE THREAD

**Issue by Missingno255** [spiritualized1997/openFPGA-GB-GBC#33]
Certain GBC games (denoted in the No-Intro set as "GB Compatible") like Bomberman Quest, Pokémon Gold/Silver, and Tetris DX for example, do not show up under the Gameboy core.

**Comment by MaciekBaron** [comment]
That's just an extension problem, change it to .gb and you're good to go

**Comment by Missingno255** [comment]
> That's just an extension problem, change it to .gb and you're good to go

That should be mentioned on the readme, so people don't get confused and assume it's a problem with the core.
