### ISSUE TITLE
Files with apostrophes do not appear for GB / GBC

### ISSUE THREAD

**Issue by JJMilez** [spiritualized1997/openFPGA-GB-GBC#38]
SD card directory for GB, viewed on laptop:
<img width="300" src="https://user-images.githubusercontent.com/124460713/216783013-0ae6f67c-9ec9-4ba2-b708-7746a428ff59.png">

The same directory, viewed on Pocket:
<img width="300" src="https://user-images.githubusercontent.com/124460713/216783072-401dab5a-9ecd-4c0e-8904-2e67ef60b046.jpeg">

It is possible other special characters are also affected, but so far I've only noticed this issue with apostrophes. In this case, both Link's Awakening in the GB folder and Link's Awakening DX in the GBC folder were not appearing. I initially dismissed the apostrophe because the GBA core correctly displays files like Yoshi's Island.

Steps to reproduce:
- Rename any working-as-expected file to include an apostrophe
- Observe the file no longer appears when loaded on Pocket

**Comment by italiangrandma** [comment]
Just checked this and titles with apostrophes are displaying just fine. This is with the latest firmware v1.1 (rel. 5/4/23)
![image](https://user-images.githubusercontent.com/64335992/236594936-67802b51-3805-4161-a28c-a2e07098a83b.jpeg)

**Comment by JJMilez** [comment]
Interesting… I just updated to v1.1 and I’m still not seeing any files with apostrophes in GBC. I’ll continue troubleshooting; the fact that this isn’t a universal issue implies there’s something I may be able to do to fix it. When I figure out what the X factor is, I’ll update here for anyone else experiencing this and close the issue.

**Comment by JJMilez** [comment]
<img width="416" alt="Screenshot 2023-08-04 at 10 52 17 PM" src="https://github.com/spiritualized1997/openFPGA-GB-GBC/assets/124460713/b7d1d425-0a54-4b2d-9d3b-28462f0eefbb">

The problem was never the core; it was actually a character in the file names that was not actually an apostrophe. Manually renaming all the affected files resolved my issue.
